apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: shuffle-kstreams
  name: shuffle-kstreams
spec:
  selector:
    matchLabels:
        app: shuffle-kstreams
  endpoints:
    - port: metrics
      interval: 10s
