apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-kstreams-ft
spec:
  benchmark: shuffle-kstreams
  load:
    loadType: "MessagesPerSecond"
    loadValues: [100000]
  resources:
    resourceType: "Instances"
    resourceValues: [8]
  slos:
    - name: input_throughput_2s
      properties:
        warmup: 300 # in seconds
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
    duration: 3360 # kill starts at 8 and kills pods every 5 minutes | pod crash every 10 mins 5 times starts at 3
    loadGenerationDelay: 60 # in seconds
    repetitions: 1
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "KAFKA_TOPIC_INPUT"
      value: "input"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "KAFKA_TOPIC_OUTPUT"
      value: "output"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "20000"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "CONSUMER_OUTPUT_RATE"
      value: "1"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "MATCHER_ZIPF_TOTAL_SELECTIVITY"
      value: "0.5"
#    - patcher:
#        type: "EnvVarPatcher"
#        resource: "shuffle-kstreams-deployment.yaml"
#        properties:
#          container: "shuffle-kstreams"
#          variableName: "MATCHER_ZIPF_TOTAL_SELECTIVITY"
#      value: "0.5"
#    - patcher:
#        type: "EnvVarPatcher"
#        resource: "shuffle-kstreams-deployment.yaml"
#        properties:
#          container: "shuffle-kstreams"
#          variableName: "CONSUMER_OUTPUT_RATE"
#      value: "1"
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "KAFKASTREAMS__COMMIT_INTERVAL_MS__"
      value: "2000"

#    - patcher:
#        type: "EnvVarPatcher"
#        resource: "shuffle-kstreams-deployment.yaml"
#        properties:
#          container: "shuffle-kstreams"
#          variableName: "KAFKASTREAMS__PARTITION_ASSIGNMENT_STRATEGY__"
#      value: "RoundRobin"


#    - patcher:
#        type: "EnvVarPatcher"
#        resource: "shuffle-kstreams-deployment.yaml"
#        properties:
#          container: "shuffle-kstreams"
#          variableName: "KAFKASTREAMS__PROCESSING_GUARANTEE__"
#      value: "exactly_once_v2"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          variableName: "type"
      value: "workers"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
