apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-spark-ft
spec:
  benchmark: shuffle-spark
  load:
    loadType: "MessagesPerSecond"
    loadValues: [100000]
  resources:
    resourceType: "Instances"
    resourceValues: [8]
  slos:
    - name: input_throughput_2s
      properties:
        warmup: 300 # in seconds
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
#    duration: 320 # in seconds (start at minute 3 and have a failure every 10 minutes)
    duration: 3360 # kill starts at 8 and kills pods every 5 minutes | pod crash every 10 mins 5 times starts at 3
    loadGenerationDelay: 60 # in seconds
    repetitions: 1
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          container: "spark-submit"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "20000"
    - patcher:
        type: "EnvVarPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          container: "spark-submit"
          variableName: "SPARK_SQL_SHUFFLE_PARTITIONS"
      value: "16"

    - patcher:
        type: "EnvVarPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          container: "spark-submit"
          variableName: "CONSUMER_OUTPUT_RATE"
      value: "1"
    - patcher:
        type: "EnvVarPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          container: "spark-submit"
          variableName: "MATCHER_ZIPF_TOTAL_SELECTIVITY"
      value: "0.5"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "spark-master-deployment.yaml"
        properties:
          variableName: "type"
      value: "manager"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "spark-worker-deployment.yaml"
        properties:
          variableName: "type"
      value: "workers"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
