apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuffle-hzcast
spec:
  selector:
    matchLabels:
      app: shuffle-hzcast
  replicas: 9
  template:
    metadata:
      labels:
        app: shuffle-hzcast
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: shuffle-hzcast
          image: ghcr.io/dynatrace-research/shufflebench/shuffle-hzcast:latest
          ports:
            - containerPort: 5701
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HAZELCAST_KUBERNETES_DNS_NAME
              value: "shuffle-hzcast.$(KUBERNETES_NAMESPACE).svc.cluster.local"
            - name: MATCHER_ZIPF_NUM_RULES
              value: "1000000"
            - name: MATCHER_ZIPF_TOTAL_SELECTIVITY
              value: "0.2"
            - name: MATCHER_ZIPF_S
              value: "0.0"
            - name: CONSUMER_INIT_COUNT_RANDOM
              value: "true"
            #- name: HAZELCAST_JET_JOB_PROCESSINGGUARANTEE
              #value: "NONE"
              #value: "AT_LEAST_ONCE"
              #value: "EXACTLY_ONCE"
            # - name: HAZELCAST_JET_INSTANCE_BACKUP_COUNT
            #   value: "0"
            # - name: HAZELCAST_JET_EDGE_DEFAULTS_QUEUE_SIZE
            #   value: "65536"
            # - name: HAZELCAST_JET_EDGE_DEFAULTS_PACKET_SIZE_LIMIT
            #   value: "1"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555"
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m
        - name: prometheus-jmx-exporter
          image: "solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143"
          command:
            - java
            - -XX:+UnlockExperimentalVMOptions
            - -XX:+UseCGroupMemoryLimitForHeap
            - -XX:MaxRAMFraction=1
            - -XshowSettings:vm
            - -jar
            - jmx_prometheus_httpserver.jar
            - "5556"
            - /etc/jmx-aggregation/jmx-prometheus.yml
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: jmx-config
              mountPath: /etc/jmx-aggregation
      volumes:
        - name: jmx-config
          configMap:
            name: shuffle-hzcast-jmx-configmap
