apiVersion: v1
kind: Service
metadata:  
  name: shuffle-hzcast
  labels:
    app: shuffle-hzcast
spec:
  type: ClusterIP
  clusterIP: None
  selector:    
    app: shuffle-hzcast
  ports:  
    - name: coordination
      port: 5701
      targetPort: 5701
      protocol: TCP
    - name: metrics
      port: 5556
