apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuffle-latency-exporter
spec:
  selector:
    matchLabels:
      app: shuffle-latency-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: shuffle-latency-exporter
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: shuffle-latency-exporter
          image: shufflebench/latency-exporter:latest # Adjust image to yours
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
      nodeSelector:
        type: infra