apiVersion: v1
kind: Service
metadata:
  name: shuffle-latency-exporter
  labels:
    app: shuffle-latency-exporter
spec:
  selector:
    app: shuffle-latency-exporter
  ports:
  - name: metrics
    port: 8080
