apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  labels:
    app: flink
spec:
  selector:
    app: flink
    component: jobmanager
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: blob-server
      port: 6124
    - name: webui
      port: 8081
    - name: metrics
      port: 9249
