apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  labels:
    app: flink
spec:
  selector:
    app: flink
    component: taskmanager
  type: ClusterIP
  ports:
    - name: metrics
      port: 9249
  